name: Docker

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-dev[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v1

      - id: get_version
        run: echo "::set-output name=version::$(<VERSION)"

      - run: echo ${{ steps.get_version.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish Base Container 🐳
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/base/Dockerfile
          push: true
          tags: labshare/polus-bfio-util:${{ steps.get_version.outputs.version-without-v }}

      - name: Publish Tensorflow Container 🐳
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/tensorflow/Dockerfile
          push: true
          tags: labshare/polus-bfio-util:${{ steps.get_version.outputs.version-without-v }}-tensorflow

      - name: Publish ImageJ Container 🐳
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/imagej/Dockerfile
          push: true
          tags: labshare/polus-bfio-util:${{ steps.get_version.outputs.version-without-v }}-imagej
