name: Docker

on:
  push:
    branches:
      - master
      - dev
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v1

      - id: get_version
        uses: battila7/get-version-action@v2

      - run: echo ${{ steps.get_version.outputs.is-semver }}
      - run: echo ${{ steps.get_version.outputs.version-without-v }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish Docker Container 🐳
        if: ${{ steps.get_version.outputs.is-semver }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/base/Dockerfile
          push: true
          tags: labshare/polus-bfio-util:${{ steps.get_version.outputs.version-without-v }}
