name: Python Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  unittest:
    name: Run unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-latest]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          python -m pip install ome-types==0.3.4
          python -m pip install xmlschema
          pip install .[dev]
      - name: Test with unittest
        run: |
          python -m unittest
