name: Python Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  unittest:
    name: unittest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies 🔧
        run: |
          sudo apt update
          sudo apt install openjdk-11-jdk -y
          python -m pip install --upgrade pip
          python -m pip install ome-types==0.3.4
          python -m pip install xmlschema
          pip install .[dev]
      - name: Test with unittest
        run: |
          python -m unittest
